apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: cat-service
    visualize: "true"
  name: cat-service-canary
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cat-service
        tier: backend
        track: canary
        run: cat-service
        visualize: "true"
    spec:
      containers:
      - image: rpicloud/demo-cat-service:v2
        name: cat-service-canary
  minReadySeconds: 120
