apiVersion: v1
kind: Service
metadata:
  labels:
    app: cat-service
    tier: backend
    run: cat-service
    visualize: "true"
  name: cat-service
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: cat-service
    tier: backend
